version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-dev
      args:
        # To authenticate to private registry either use username / password, or Oauth key/secret / etc
        # Please add Composer Auth JSON Object
        COMPOSER_AUTH: "{}"
        APP_BASE_DIR: ${APP_BASE_DIR-.}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ${APP_BASE_DIR-.}:/app


  web:
    build:
      context: .
      target: web-dev
      args:
        APP_BASE_DIR: ${APP_BASE_DIR-.}
    restart: unless-stopped
    ports:
      - 9010:9000
    environment:
      # The Hostname for the FPM (needs to match the hostname for the `app`)
      PHP_FPM_HOST: app
      TZ: America/Sao_Paulo
    volumes:
      - ${APP_BASE_DIR-.}/public:/app/public
    depends_on:
      - app
